# fly.toml file generated for authssh on 2023-04-07T17:02:46-05:00

app = "authssh"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4202
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  [[services.ports]]
    handlers = []
    port = 22
